package algonquin.cst2335.finalproject;

import androidx.room.Database;
import androidx.room.RoomDatabase;

/**
 * Abstract database class that serves as the main connection to the application's persisted data.
 * Defines the database configuration and serves as the app's main access point to the persisted data.
 *
 * @author Aditya Hirpara */

/**
 * Abstract database class that serves as the main connection to the application's persisted data.
 * This class defines the database configuration and serves as the app's main access point to the persisted data.
 *
 * Entities represent the tables in the database. Each entity corresponds to a table that will be created in the database.
 * Version defines the version of the database. It should be incremented upon any schema change.
 */
@Database(entities = {Location.class}, version = 1)
public abstract class AppDatabase extends RoomDatabase {

    /**
     * Gets the Location Data Access Object (LocationDao) for the database.
     * This DAO contains methods that offer abstract access to your app's database.
     *
     * @return The LocationDao implementation generated by Room.
     */
    public abstract LocationDao locationDao();
}